CREATE TABLE [dbo].[Todo]
(
    [Id] UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_Todo PRIMARY KEY
        DEFAULT NEWID(),

    [UserId] UNIQUEIDENTIFIER NOT NULL,

    [Title] NVARCHAR(255) NOT NULL,

    [IsDone] BIT NOT NULL
        CONSTRAINT DF_Todo_IsDone DEFAULT 0,

    [CreatedAt] DATETIME2 NOT NULL
        CONSTRAINT DF_Todo_CreatedAt DEFAULT GETDATE(),

    CONSTRAINT FK_Todo_User
        FOREIGN KEY ([UserId])
        REFERENCES [dbo].[User]([Id])
        ON DELETE CASCADE
);